version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    # Verificar se o mysql está em pé
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    # vai esperar o container ficar 100% online para subir o outro.
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    ports:
      - 3306:3306

    

networks: 
  node-network:
    driver: bridge      